// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNHZUv-BNJgV4h1WUBme6MwE-OoTrJvZ0',
    appId: '1:1040804498442:web:dd6c23c6fb0426ac75e3f3',
    messagingSenderId: '1040804498442',
    projectId: 'stay-safe-app-ee141',
    authDomain: 'stay-safe-app-ee141.firebaseapp.com',
    storageBucket: 'stay-safe-app-ee141.firebasestorage.app',
    measurementId: 'G-M0S1RZKMNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXVqGJEH03Jx_KuAkVXyrhCzgkqWZcGU',
    appId: '1:1040804498442:android:f944458e47eda99a75e3f3',
    messagingSenderId: '1040804498442',
    projectId: 'stay-safe-app-ee141',
    storageBucket: 'stay-safe-app-ee141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXs8VJyZoC65tG8GsJ9BhjlaIOUoHI7w',
    appId: '1:1040804498442:ios:2724650086367a8f75e3f3',
    messagingSenderId: '1040804498442',
    projectId: 'stay-safe-app-ee141',
    storageBucket: 'stay-safe-app-ee141.firebasestorage.app',
    iosBundleId: 'com.example.staySafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXs8VJyZoC65tG8GsJ9BhjlaIOUoHI7w',
    appId: '1:1040804498442:ios:2724650086367a8f75e3f3',
    messagingSenderId: '1040804498442',
    projectId: 'stay-safe-app-ee141',
    storageBucket: 'stay-safe-app-ee141.firebasestorage.app',
    iosBundleId: 'com.example.staySafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNHZUv-BNJgV4h1WUBme6MwE-OoTrJvZ0',
    appId: '1:1040804498442:web:55b3c011753b801c75e3f3',
    messagingSenderId: '1040804498442',
    projectId: 'stay-safe-app-ee141',
    authDomain: 'stay-safe-app-ee141.firebaseapp.com',
    storageBucket: 'stay-safe-app-ee141.firebasestorage.app',
    measurementId: 'G-YHQ3HY801B',
  );

}